{application,log_provider,
             [{description,"An OTP library"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{log_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[lib_log,log,log_server]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
